gazebo_ros_control/pid_gains:
    # Publish all joint states -----------------------------------
    joint_state_controller:
      type: joint_state_controller/JointStateController
      publish_rate: 50  

    # Position Controllers ---------------------------------------
    joint_s:
      {p: 100.0, i: 0.01, d: 10.0}

    joint_l:
      {p: 100.0, i: 0.01, d: 10.0}  

    joint_e:
      {p: 100.0, i: 0.01, d: 10.0}

    joint_u:
      {p: 100.0, i: 0.01, d: 10.0}
     
    joint_r:
      {p: 100.0, i: 0.01, d: 10.0}
    
    joint_b:
      {p: 100.0, i: 0.01, d: 10.0}
    
    joint_t:
      {p: 100.0, i: 0.01, d: 10.0}

    # joint_l_position_controller:
    #   type: position_controllers/JointPositionController
    #   joint: joint_l
    #   pid: {p: 100.0, i: 0.01, d: 10.0}
      
    # joint_e_position_controller:
    #   type: position_controllers/JointPositionController
    #   joint: joint_e
    #   pid: {p: 100.0, i: 0.01, d: 10.0}
      
    # joint_u_position_controller:
    #   type: position_controllers/JointPositionController
    #   joint: joint_u
    #   pid: {p: 100.0, i: 0.01, d: 10.0}
      
    # joint_r_position_controller:
    #   type: position_controllers/JointPositionController
    #   joint: joint_r
    #   pid: {p: 100.0, i: 0.01, d: 10.0}
      
    # joint_b_position_controller:
    #   type: position_controllers/JointPositionController
    #   joint: joint_b
    #   pid: {p: 100.0, i: 0.01, d: 10.0}
      
    # joint_t_position_controller:
    #   type : position_controllers/JointPositionController  
    #   joint: joint_t  
    #   pid: {p: 100.0, i: 0.01, d: 10.0}
